FROM rustlang/rust:nightly-bookworm-slim AS cacher
WORKDIR /app

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    mold \
    clang \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-chef sccache --locked
RUN rustup component add rustc-codegen-cranelift-preview --toolchain nightly

FROM cacher AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json --bin frontdoor


FROM cacher AS builder
COPY --from=planner /app/recipe.json recipe.json

ENV RUSTC_WRAPPER=sccache \
    SCCACHE_DIR=/sccache \
    RUSTFLAGS="-C linker=clang -C link-arg=-fuse-ld=mold"

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=$SCCACHE_DIR \
    cargo chef cook --recipe-path recipe.json --bin frontdoor

COPY . .

RUN mkdir -p .cargo && \
    printf "[unstable]\ncodegen-backend = true\n\n[profile.dev]\ncodegen-backend = \"cranelift\"\n" \
        > .cargo/config.toml

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=$SCCACHE_DIR \
    cargo build --bin frontdoor

FROM debian:bookworm-slim AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y \
    ca-certificates \
    libssl3 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/debug/frontdoor /usr/local/bin/frontdoor

ENTRYPOINT ["/usr/local/bin/frontdoor"]
