apiVersion: skaffold/v4beta13
kind: Config
profiles:
  - name: dev
    build:
      local:
        push: false
        concurrency: 0
      artifacts:
        - image: degov/chancelor
          context: .
          docker:
            dockerfile: deployment/docker/chancelor/Dockerfile.dev
        - image: degov/kube-operator
          context: .
          docker:
            dockerfile: deployment/docker/kube-operator/Dockerfile.dev
        - image: degov/frontdoor
          context: .
          docker:
            dockerfile: deployment/docker/frontdoor/Dockerfile.dev
        - image: degov/office
          context: .
          docker:
            dockerfile: deployment/docker/office/Dockerfile.dev
    deploy:
      helm:
        releases:
          - name: degov
            chartPath: deployment/helm/degov
            namespace: degov
            setValues:
              image.repository: degov
              image.tag: skaffold
              frontdoor.ingress.enabled: true
              frontdoor.ingress.hosts:
                - host: frontdoor.localhost
                  paths:
                    - path: /
                      pathType: Prefix
              office.ingress.enabled: true
              office.ingress.hosts:
                - host: office.localhost
                  paths:
                    - path: /
                      pathType: Prefix
            skipBuildDependencies: true
