FROM node:22-slim AS base

WORKDIR /app

FROM base AS prepare
RUN npm install -g turbo@^2

COPY . .

RUN turbo prune office --docker

FROM base AS builder
WORKDIR /app

RUN npm install -g pnpm@10.18.0

COPY --from=prepare /app/out/json/ .

RUN --mount=type=cache,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

COPY --from=prepare /app/out/full/ .
RUN --mount=type=cache,target=/app/.turbo \
    pnpm build

FROM nginx:alpine

COPY --from=builder /app/apps/office/dist /usr/share/nginx/html

COPY deployment/docker/office/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

